#pragma once 

#define TP_NOTIFICATION_UPDATE_LOBBY_SCORE "TexasPoker_notification_update_lobby_score"
#define TP_NOTIFICATION_UPDATE_SCORE  "updatejifen"

#define TP_PATH_BACKGROUND_MUSIC				"TexasPoker/music/bg_music.mp3"
#define TP_TABLE_DIZHU_NUM						"TexasPoker/image/table_dizhu_num.png"
#define TP_IMAGE_PATH_GAMEBANK					"TexasPoker/image/gamebank/"
#define TP_IMAGE_PATH_INGAEM					"TexasPoker/image/ingame/"
#define TP_IMAGE_PATH_TABLE						"TexasPoker/image/tablelist/"
#define TP_IMAGE_PATH_HEADER					"TexasPoker/image/header/"
#define TP_IMAGE_PATH_CARDTYPE_EFFECT			"TexasPoker/image/cardTypeEffect/"
#define TP_IMAGE_PATH_CARD_EFFECT				"TexasPoker/image/cardEffect/"
#define TP_IMAGE_PATH_HEGUAN_EFFECT				"TexasPoker/image/heguanEffect/"
#define TP_IMAGE_PATH_ACTIVITY					"TexasPoker/image/TexasPokerActive/"
#define TP_IMAGE_PATH_GUIDE						"TexasPoker/image/guideTips/"
#define TP_IMAGE_EFFECT_PATH					"TexasPoker/image/propEffect/"
#define TEXASPOKER_IMAGE_PATH_GAMEBANK			"TexasPoker/image/gamebank/"
#define IMAGE_PATH_SETTING						"image/setting/"
#define TEXASPOKER_IMAGE_PATH_ROOMCHOICE		"TexasPoker/image/roomchoice/"
#define TEXASPOKER_IMAGE_PATH_QUICKPAY			"TexasPoker/image/quickPay/"


#define GD_LOBBY_BACKGROUND_MUSIC				"GuanDan/music/lobby_music.mp3"
#define GD_PATH_BACKGROUND_MUSIC				"GuanDan/music/gd_music.mp3"
#define GD_IMAGE_PATH_INGAME			"GuanDan/ingame/"
#define GD_IMAGE_PATH_ROOM              "GuanDan/roomlist/"
#define GD_ROBOT_EFFECT                 "GuanDan/robotEffect/"
#define GD_IMAGE_PATH_HEADER					"GuanDan/header/"
#define GD_IMAGE_PATH_BADAGE					"GuanDan/gd_badge/"
#define GD_TV_PATH_IMAGE					"GuanDanTV/"
#define GD_GUIDE_IMAGE_PATH_GUIDE			"GuanDan/guideicon/"
#define GD_IMAGE_PATH_MATCH			"GuanDan/match/"
#define GD_IMAGE_PATH_PRIVATE			"GuanDan/private/"